version: "3"

services:
  proxy:
    # The official v2 Traefik docker image
    image: traefik:v2.1
    container_name: proxy

    ports:
      # The HTTP port
      - "80:80"
      # The secure HTTPS port
      - "443:443"
      # The Web UI (enabled by --api.insecure=true)
      - "8080:8080"
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.yml:/traefik.yml
      - ./traefik.log:/traefik.log
      # documento para generar certificados
      - ./acme.json:/acme.json

  front:
    image: nginx
    container_name: front
    labels:
      - "traefik.http.routers.front.rule=Host(`reportshcg.com`)"
    # habilitar lineas para activar ssl
      - "traefik.http.routers.front.entrypoints=websecure"
      - "traefik.http.routers.front.tls.certresolver=resolver"
    restart: always
    volumes:
      - /usr/share/zoneinfo/America/Bogota:/etc/localtime
      - ./front/dist/front/:/usr/share/nginx/html/
      - ./nginx/:/etc/nginx/

  back:
    image: node
    container_name: back
    labels:
      - "traefik.http.routers.back.rule=Host(`data.back.reportshcg.com`)"
      - "traefik.http.services.back.loadbalancer.server.port=3000"
      # habilitar lineas para activar ssl
      - "traefik.http.routers.back.entrypoints=websecure"
      - "traefik.http.routers.back.tls.certresolver=resolver"
    restart: always
    working_dir: /home/node/thegraph
    environment:
      - NODE_ENV=production
    volumes:
      - ./back/:/home/node/thegraph

    command: "npm start"

  mssql:
    image: microsoft/mssql-server-linux:latest
    container_name: mssql
    labels:
      - traefik.enable=true
      - traefik.tcp.routers.mssql.rule=HostSNI(`db.reportshcg.com`)
      - traefik.tcp.routers.mssql.tls=true
      - traefik.tcp.routers.mssql.service=mssql
      - traefik.tcp.services.mssql.loadbalancer.server.port=1433
    volumes:
      - ./mssql/data:/var/opt/mssql/data
    restart: always
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=4dm1nPr0c
